966 Routing configuration: Extbase routeEnhancer example not consistent
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1009
Opened 2020-10-07 16:31 UTC by susannemoog

The example was incomplete and inconsistent and has been adjusted to be more realistic (taken from the real news extension as inspiration).

Resolves: #996

2020-10-07 16:44 UTC, sypets commented
> Resolves: #996
This is a PR. Wrong issue number?

2020-10-07 16:50 UTC, susannemoog commented
> 
> 
> > Resolves: #996
> > This is a PR. Wrong issue number?

Those numbers start to look the same ;) 966 is correct.

2020-10-08 06:38 UTC, mbrodala requested changes

2020-10-08 06:38 UTC, mbrodala commented on Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
> +         news-title:
This must be `news_title` instead AFAIS.

2020-10-08 06:38 UTC, mbrodala commented on Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
> +         tag-name:
Same here: this should be `tag_name` instead.

2020-10-08 12:41 UTC, mbrodala approved these changes

2020-10-08 12:42 UTC, merged