[FEATURE] Add JavaScript Modal API
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1042
Opened 2020-10-17 09:52 UTC by susannemoog

See Core Feature 90168 
See Core Feature 63729
See #845

2020-10-17 12:39 UTC, andreasfernandez requested changes

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +Actions that require a users' attention must be visualized by modal windows.
afaik it must be "require a user's".

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +if actions (buttons) are attached to the modal, one button must be a positive action. This button
I don't get the last sentence.

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +Data-Attributes
superfluous dash

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +data-severity             the severity for the modal, default is info (see TYPO3.Severity.*)
:code:\`TYPO3.Severity.*\`

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +Modals should be used rarely and only for confirmations. For information the TYPO3.Flashmessage API should be used.
:code:\`TYPO3.Flashmessage\`

2020-10-17 12:39 UTC, andreasfernandez commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +severity  int                          Represents the severity of a modal. Please see TYPO3.Severity. Default is :code:`TYPO3.Severity.info`.
:code:\`TYPO3.Severity\`

2020-10-20 04:28 UTC, flicstar commented on Documentation/ApiOverview/JavaScript/Modules/Index.rst
> +A basic modal without any specials can be created this way:
```suggestion
A basic modal (without anything special) can be created this way:
```
OR A basic modal can be created this way:

2020-10-20 07:51 UTC, andreasfernandez approved these changes

2020-10-20 07:56 UTC, merged