Update Index.rst
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1115
Opened 2020-11-20 14:35 UTC by hmccloy

There is an error in the doc:
For a JSON respone your have to use JsonResponse (which implements Response)

2020-11-20 14:39 UTC, mbrodala commented
Actually you should not use the `JsonResponse` class since it is `@internal`:

https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/core/Classes/Http/JsonResponse.php#L23

Instead you should use the `ResponseFactoryInterface` as described here:

https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/RequestHandling/Index.html#creating-new-request-response-objects

Can you adjust the example and link to that page instead?

2020-11-20 14:40 UTC, mbrodala requested changes

2020-11-20 14:40 UTC, mbrodala commented on Documentation/ApiOverview/Ajax/Backend/Index.rst
> +       return new JsonResponse(['result' => $result], 200);
See comment.

2020-12-18 11:44 UTC, marble commented
@hmccloy 

> Can you adjust the example and link to that page instead?

2020-12-29 16:41 UTC, linawolf commented
I had to integrate the commit in another PR, so that I can edit it. See #1223

2020-12-29 16:41 UTC, closed without merging