Update title for BE module API
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1173
Opened 2020-12-14 12:15 UTC by sypets

Information on this page is Extbase-specific

2020-12-14 16:01 UTC, linawolf requested changes

2020-12-17 08:49 UTC, linawolf approved these changes

2020-12-17 08:50 UTC, linawolf commented
I made my changes, are you ok with that, @sypets ?

2020-12-17 09:32 UTC, marble approved these changes

2020-12-17 09:32 UTC, merged