Feature index E
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1175
Opened 2020-12-15 08:39 UTC by linawolf

Also moved pictures from 
Documentaion/ApiOverview/ExtensionScanner/Images
And renamed them to CamelCase

2020-12-15 16:50 UTC, marble commented on Documentation/ApiOverview/ExtensionScanner/Index.rst
> +.. index:: Admin tool; Scan Extension Files
IMHO should be: `Scan extension files` in normal text and the alt text of images. And in the index therefore too, no matter what the guilabel says. Or, if you insist for the index: write `Admin tool; 'Scan Extension Files'`

2020-12-15 16:51 UTC, marble commented on Documentation/ApiOverview/ExtensionScanner/Index.rst
> +.. index:: Extension Scanner
But this is `Extension scanner` in the following headline. I guess that's what should be considered right?!

2020-12-15 16:57 UTC, marble commented on Documentation/ApiOverview/DependencyInjection/Index.rst
> +.. index::Dependency injection; Public
Add space after index::

2020-12-15 17:00 UTC, marble requested changes
1. Please see inline comments
2. Add a space after index:: , one file is affected. It is what we usually have and moreover, I think it is mandatory.

2020-12-15 18:55 UTC, linawolf commented on Documentation/ApiOverview/DependencyInjection/Index.rst
> +.. index::Dependency injection; Public
yeah, copy and paste...

2020-12-16 08:10 UTC, marble approved these changes

2020-12-16 08:10 UTC, merged