[FEATURE] Add indexes to ApiOverview - letter B - C
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1176
Opened 2020-12-15 15:09 UTC by linawolf

New PR since the old one got mixed up in trying to resolve a conflict

2020-12-15 15:17 UTC, gilbertsoft requested changes

2020-12-15 15:17 UTC, gilbertsoft commented on Documentation/ApiOverview/BackendLayout/Index.rst
> +Since TYPO3 4.5 there has been a database record type "backend Layout" to define a combination of rows and columns
```suggestion
Since TYPO3 4.5 there has been a database record type "backend layout" to define a combination of rows and columns
```

2020-12-15 15:17 UTC, gilbertsoft commented on Documentation/ApiOverview/BackendLayout/Index.rst
> +Backend layouts can be configured either as "backend ayout" record in a sysfolder or as Page TSconfig entry in
```suggestion
Backend layouts can be configured either as "backend layout" record in a sysfolder or as Page TSconfig entry in
```

2020-12-15 15:17 UTC, gilbertsoft commented on Documentation/ApiOverview/BackendLayout/Index.rst
>  ================================
```suggestion
====================
```

2020-12-15 17:04 UTC, marble commented on Documentation/ApiOverview/BackendLayout/Index.rst
> +.. index:: !Backend Layout
Shouldn't it be `Backend layout`?!

2020-12-15 17:08 UTC, marble commented on Documentation/ApiOverview/BackendLayout/Index.rst
> +Backend layouts can be configured either as "backend layout" record in a sysfolder or as Page TSconfig entry in
Later on it is `page TSconfig` in this paragraph

2020-12-15 17:13 UTC, marble requested changes
Please see inline comments

2020-12-15 17:48 UTC, linawolf commented on Documentation/ApiOverview/BackendLayout/Index.rst
> +.. index:: !Backend Layout
Ja, Gra!

2020-12-16 08:08 UTC, marble approved these changes

2020-12-16 08:08 UTC, merged