Always exclude Domain/Model from DI container
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1397
Opened 2021-05-21 06:39 UTC by vertexvaar

The symfony DI component should not scan the Model directory for following reasons:
* They are not services
* They shouldn't need DI injection
* They are almost never created using the DI container and if, problems with the extbase persistence will occurr.
* Symfony excludes Entities by default, too

2021-05-21 06:47 UTC, mbrodala requested changes

2021-05-21 06:47 UTC, mbrodala commented on Documentation/ApiOverview/CommandControllers/Index.rst
> +         exclude: '../Classes/Domain/Model/*'
This should be moved to the general DI description instead:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html

Also we should add an explanation about this on that page.

Finally we could reduce this code snippet to the command and link to that page.

2021-05-29 10:14 UTC, linawolf commented
@mbrodala please have another look at this one

2021-06-12 10:09 UTC, linawolf approved these changes

2021-06-12 10:09 UTC, merged