[IMPORTANT] #94312 - Removed BE/loginSecurityLevel and FE/loginSecuri…
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1428
Opened 2021-06-26 10:27 UTC by linawolf

…tyLevel options

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395

2021-07-02 09:16 UTC, tomwarwick requested changes

2021-07-02 09:16 UTC, tomwarwick commented on Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
> +   This option got removed with version 11.3. The only possible
(Adjust wording)
This was removed in version 11.3

2021-07-02 09:16 UTC, tomwarwick commented on Documentation/ApiOverview/GlobalValues/Typo3ConfVars/FE.rst
> +   This option got removed with version 11.3. The only possible
This was option was removed in 11.3

2021-07-03 09:19 UTC, susannemoog approved these changes

2021-07-06 08:36 UTC, merged