[FEATURE] #94374 - Create new filemount via folders’ context menu
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1431
Opened 2021-06-26 16:30 UTC by linawolf

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395

2021-07-02 09:31 UTC, tomwarwick requested changes

2021-07-02 09:31 UTC, tomwarwick commented on Documentation/ApiOverview/AccessControl/MoreAboutFileMounts/Index.rst
> +folder and choose :guilabel:`New Filemount`. Then give the new filemount a name.
Replace period with a comma.

2021-07-03 07:37 UTC, linawolf commented on Documentation/ApiOverview/AccessControl/MoreAboutFileMounts/Index.rst
> +folder and choose :guilabel:`New Filemount`. Then give the new filemount a name.
Which one? Both?

2021-07-06 08:40 UTC, tomwarwick commented on Documentation/ApiOverview/AccessControl/MoreAboutFileMounts/Index.rst
> +folder and choose :guilabel:`New Filemount`. Then give the new filemount a name.
Second one , after 'New Filemount'.

2021-07-06 14:12 UTC, susannemoog approved these changes

2021-07-06 14:34 UTC, merged