Describe the semantic of the selected doktype
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1484
Opened 2021-08-11 10:03 UTC by jnugh

Doktypes should not be selected randomly. The TYPO3 behavior changes if a doktype number larger than 199 is being selected.

2021-08-11 10:09 UTC, mbrodala commented
Are you sure this is still valid?

See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Important-18079-PagesdoktypeRestrictionForFrontendQueriesRefined.html

2021-08-11 10:22 UTC, mbrodala requested changes

2021-08-11 10:22 UTC, mbrodala commented on Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
> +   doktype is less than 199. If oyu select a higher number the page will be handled like a
```suggestion
   doktype is less than 199. If you select a higher number the page will be handled like a 
```

2021-08-11 10:22 UTC, mbrodala commented
Can you link here the specific location in the TYPO3 source where this happens?

2021-08-11 11:26 UTC, jnugh commented
Can be found here, still valid in master as far as I can tell. Maybe it's not intended anymore and should not be documented but changed instead?
https://github.com/TYPO3/typo3/blob/master/typo3/sysext/backend/Classes/Tree/View/ElementBrowserPageTreeView.php#L143

2021-08-11 11:30 UTC, mbrodala commented
Indeed, I don't see why keeping this constraint would make sense. Can you report an issue? I've converted this PR to a draft for now until it is clear which way we go.

2021-08-11 11:53 UTC, jnugh commented
I was able to find this one: https://forge.typo3.org/issues/94430

2021-08-11 13:13 UTC, mbrodala commented
Nice one, that one indeed seems to sum up the remaining restrictions. Let's see into getting these resolved.

2022-04-15 09:40 UTC, typecat commented
According to the forge ticket, this issue has been fixed for version 11, so this note doesn't apply anymore. Therefore, I close this PR.

2022-04-15 09:40 UTC, closed without merging