[Feature] #95364 Add ModifyHrefLangTagsEvent
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1543
Opened 2021-10-02 07:55 UTC by linawolf

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95364-EventToModifyFrontendUserGroupsWithoutAuthentication.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522

2021-10-03 14:43 UTC, brotkrueml requested changes

2021-10-03 14:43 UTC, brotkrueml commented on Documentation/ApiOverview/Hooks/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
> +.. index:: Events; ModifyHrefLangTagsEvent
"ModifyHrefLangTagsEvent" should be: "ModifyResolvedFrontendGroupsEvent"

2021-10-03 14:43 UTC, brotkrueml commented on Documentation/ApiOverview/Hooks/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
> +.. _ModifyHrefLangTagsEvent:
same here

2021-10-03 14:43 UTC, brotkrueml commented on Documentation/ApiOverview/Hooks/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
> +ModifyHrefLangTagsEvent
same here

2021-10-04 13:43 UTC, tomwarwick approved these changes

2021-10-04 13:44 UTC, merged