Breaking: #96287 - Doctrine DBAL 3.2
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1637
Opened 2021-12-12 09:58 UTC by linawolf

references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

releases: master, 11.4

2021-12-12 09:58 UTC, linawolf commented
Do not merge without an ok from @lolli42

2021-12-12 13:07 UTC, sbuerk requested changes
Thanks for your work Lina, but I have minor remarks which should be addressed.

2021-12-12 13:07 UTC, sbuerk commented on Documentation/Testing/ExtensionTesting.rst
>              $count = $queryBuilder->count('uid')
We should add a (int) cast here. It may be not an integer which is returned (for ex. with sqlite and PHP before 8.1)

2021-12-12 13:07 UTC, sbuerk commented on Documentation/Testing/ExtensionTesting.rst
>              $count = $queryBuilder->count('uid')
Same here, (int) cast

2021-12-13 07:23 UTC, linawolf commented on Documentation/ApiOverview/Database/Statement/Index.rst
> -Statement
We will update the prepared statement section lateron. This chapter never described more then how to get the results. The change doesn't hinder us from explaining statements in DBAL context lateron

2021-12-13 08:04 UTC, linawolf commented on Documentation/ApiOverview/Workspaces/Index.rst
> +      $row = $result->fetchAssociative();
I added a todo, I think we cannot solve this from the scope of this issue.

2021-12-13 08:06 UTC, linawolf commented on Documentation/ApiOverview/Database/Statement/Index.rst
> +:php:`->fetchAssociative()` returns arrays with single field / values pairs
Updated it

2021-12-13 08:13 UTC, linawolf commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
could you make another PR about this one?

2021-12-13 08:20 UTC, linawolf commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +.. versionchanged:: 12.0
I rephrased this to make the relation to Doctrine DBAL 3.2 more clear. Doctrine DBAL 3.2 has been introduced with 12 not with 11. We can still put another message hinting to the migration plan in v11 here.

2021-12-13 08:49 UTC, linawolf commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +      ->executeQuery();
The double point combined with an indentation creates a code-block, it is a short-command... 

Should we put a todo that the example needs to be rebuild?

2021-12-13 08:52 UTC, sbuerk commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +.. versionchanged:: 12.0
Yes, but as said, in the core provided QueryBuilder we have added these two methods on our own, and also backported to v11. That's working independent from doctrine/dbal version.

2021-12-13 08:54 UTC, sbuerk commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +      ->executeQuery();
Either the todo - or take out at least the "and JOIN expression".

2021-12-13 08:54 UTC, sbuerk commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
At a later point, yes.

2021-12-13 08:55 UTC, sbuerk commented on Documentation/ApiOverview/Database/Statement/Index.rst
> -Statement
Ack.

2021-12-19 07:19 UTC, linawolf commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +.. versionchanged:: 12.0
So what kind of formulation shall we use here?

2021-12-19 07:19 UTC, linawolf commented
@sbuerk what else is needed to get this merged?

2021-12-19 09:39 UTC, sbuerk commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +.. versionchanged:: 12.0
.. versionchanged:: 11.5.4

2021-12-19 09:50 UTC, sbuerk requested changes

2021-12-19 09:50 UTC, sbuerk commented on Documentation/Testing/ExtensionTesting.rst
> +            $count = (int) $queryBuilder->count('uid')
without space between cast and variable

2021-12-19 09:50 UTC, sbuerk commented on Documentation/Testing/ExtensionTesting.rst
> +            $count = (int) $queryBuilder->count('uid')
without space between cast and variable

2021-12-19 09:50 UTC, sbuerk commented on Documentation/ApiOverview/Workspaces/Index.rst
> +
empty line superflous (one empty line too much)

2021-12-19 09:51 UTC, sbuerk commented on Documentation/ApiOverview/Workspaces/Index.rst
> +
@linawolf otherwise, beside these three small things, it's ok from my side.

2021-12-19 09:52 UTC, sbuerk commented
> @sbuerk what else is needed to get this merged?

@linawolf otherwise, beside the three small things in the review above, it's ok from my side.

2021-12-19 10:45 UTC, linawolf commented on Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> +.. versionchanged:: 12.0
we only keep two versions, but changed it to 11.5

2021-12-19 13:46 UTC, sbuerk approved these changes

2022-01-04 15:32 UTC, lolli42 approved these changes

2022-01-04 15:38 UTC, merged