add the LoggerAwareInterface
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1713
Opened 2022-02-15 17:27 UTC by franzholz

It is necessary for the understanding of the code examples.

2022-02-15 18:35 UTC, brotkrueml reviewed
Maybe I am wrong, but the topic is about channels and the added example doesn't set channels. So it is not the same.

2022-02-15 18:49 UTC, franzholz commented
This is not an example.
It is the LoggerAwareTrait from the TYPO3 Core file typo3_src-11.5.5/vendor/psr/log/Psr/Log/LoggerAwareTrait.php,

2022-02-15 19:31 UTC, brotkrueml commented
You're change request states:

    The same can be accomplished be the use of the :php:`LoggerAwareTrait` :

The code block directly from above uses the security channel, your change not. So it is not the same.

The chapter describes the way to go for TYPO3 v11+ (with dependency injection and attributes)

So, in my opinion, there is not need for giving an example which is not recommended anymore. Maybe others see it different ;-) Just my 2 cents.

2022-02-15 19:49 UTC, franzholz commented
The :php:`LoggerAwareInterface`  is not an example.
Who says that is it not recommended any more in TYPO3 11.5?
It is still needed for PHP 7.

2022-02-16 07:41 UTC, mbrodala requested changes

2022-02-16 07:41 UTC, mbrodala commented on Documentation/ApiOverview/Logging/Logger/Index.rst
> +   trait LoggerAwareTrait
It doesn't make sense to embed the trait source here, especially not when the sentence before talks about the `LoggerAwareInterface`.

Instead there should be another `MyClass` example like above using this interface and trait.

2022-03-18 08:08 UTC, linawolf commented
@franzholz Are you still working on it? No changes since one month

2022-04-23 10:14 UTC, sypets commented
Please look at the other examples on the other pages. LoggerAwareTrait is included in a number of pages:

* [QuickStart](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Logging/Quickstart/Index.html#instantiate-a-logger-for-the-current-class)
* [Logger](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Logging/Logger/Index.html#channels)

Currently, the examples are inconsistent, sometimes LoggerAwareTrait is used and sometimes dependency injection.

It looks like, DI is now the recommended option (since 11), **not LoggerAwareTrait**.

```
Instantiation
New in version 11.4: [Feature: #95044 - Support autowired LoggerInterface injection](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-95044-SupportAutowiredLoggerInterfaceInjection.html)

Constructor injection can be used to automatically instantiate the logger:

use Psr\Log\LoggerInterface;

class MyClass {
    private LoggerInterface $logger;

    public function __construct(LoggerInterface $logger) {
        $this->logger = $logger;
    }
}
```

* https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Logging/Logger/Index.html#logger
* see changelog: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-95044-SupportAutowiredLoggerInterfaceInjection.html

I recommend to not merge this PR but ensure that is it generally consistent, and if in doubt, ask in core channel.

2022-04-23 10:42 UTC, sypets commented
Please see my PR #1818

2022-04-29 18:03 UTC, linawolf commented
Solved with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1818

2022-04-29 18:03 UTC, closed without merging