[FEATURE] Feature: #82809 - Make ExtensionUtility::registerPlugin met…
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1812
Opened 2022-04-17 10:20 UTC by linawolf

…hod return plugin signature.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-82809-MakeExtensionUtilityregisterPluginMethodReturnPluginSignature.html

solves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/21

2022-04-19 08:47 UTC, tomwarwick approved these changes

2022-04-19 08:50 UTC, mbrodala requested changes

2022-04-19 08:50 UTC, mbrodala commented on Documentation/ApiOverview/FlexForms/Index.rst
> +      plugins.
```suggestion
      The method :php:`ExtensionUtility::registerPlugin()` returns the plugin signature.
```

2022-04-29 18:05 UTC, linawolf commented
@mbrodala can we get this one merged?

2022-05-02 17:05 UTC, merged