Add note about language records
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1893
Opened 2022-06-02 07:32 UTC by peterkraume

In this [StackOverflow question](https://stackoverflow.com/questions/72467813/typo3-10-4-how-to-add-available-language), a 10.4 user had difficulties to add new languages to the site configuration because he was not aware that sys_language records are necessary to do so.

I've added a hint to to the 10.4 documentation. Maybe that that hint should also be applied to these pages:
- https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/SiteHandling/Basics.html#sitehandling-basics
- https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/Languages/Index.html#languages
- https://docs.typo3.org/m/typo3/guide-frontendlocalization/10.4/en-us/SettingUpLanguages/Index.html

Feel free to improve my wording!

2022-06-02 07:38 UTC, jonaseberle approved these changes

2022-06-02 07:58 UTC, mbrodala commented
It's weird that we do not seem to have any explanation about `sys_domain` records at all. All links I know point to site languages in the end ... :thinking:

2022-06-05 09:56 UTC, linawolf requested changes
Please make changes on branch main - we can backport them then

2022-06-08 09:38 UTC, joey-beech-it approved these changes

2022-06-08 09:45 UTC, linawolf approved these changes

2022-06-08 09:46 UTC, merged

2022-06-08 09:46 UTC, linawolf commented
backport from 10.4 to 9.5 - does not apply after that