[TASK] Expand section about partials
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #1978
Opened 2022-07-14 15:03 UTC by sypets

Since this part, should replace the page "Moving repeating snippets
to partials" in the Extbase book, it should include an example.

Related: TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#536

2022-07-14 15:09 UTC, linawolf approved these changes

2022-07-15 16:05 UTC, brotkrueml requested changes

2022-07-15 16:05 UTC, brotkrueml commented on Documentation/ApiOverview/Fluid/Introduction.rst
> +   <f:render partial: "Tags" arguments="{tags: post.tags}" />
```suggestion
   <f:render partial="Tags" arguments="{tags: post.tags}" />
```

2022-07-21 09:34 UTC, linawolf commented
@brotkrueml I commited you suggestion, please review again

2022-07-21 16:32 UTC, brotkrueml approved these changes

2022-07-21 16:33 UTC, merged