Move Property Mapper from Extbase Fluid Book
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2074
Opened 2022-08-17 14:35 UTC by linawolf

Releases: main, 11.5

2022-08-17 16:10 UTC, brotkrueml requested changes
I am not sure if the PropertyMapping should go under the Controller folder. As I have no experience with property mapping by now, I assum it can also be used independend of a controller. Maybe "Model / Domain" would be better as it is about mapping of models?

2022-08-19 12:58 UTC, linawolf commented
> I am not sure if the PropertyMapping should go under the Controller folder. As I have no experience with property mapping by now, I assume it can also be used independent of a controller. Maybe "Model / Domain" would be better as it is about mapping of models?

I think Property Mapping is one very important feature of the Extbase Controller. One of the things that makes it so useful.

2022-08-19 12:59 UTC, linawolf commented on Documentation/ExtensionArchitecture/Extbase/Reference/Controller/PropertyMapping.rst
> +      public function injectPropertyMapper(PropertyMapper $propertyMapper)
With constructor injection I always have the problem, that you have to show the complete constructor so there is so much noise. I think both are äquivalent.

2022-08-19 13:21 UTC, brotkrueml commented
> I think Property Mapping is one very important feature of the Extbase Controller. One of the things that makes it so useful.

Fine, then I have to dig into and use it :-)

2022-08-20 11:12 UTC, linawolf commented on Documentation/ExtensionArchitecture/Extbase/Reference/Controller/PropertyMapping.rst
> +it won't map sub properties for security reasons:
section was removed

2022-08-22 15:50 UTC, brotkrueml commented
I don't like the blog_example to be used here. First: The code is not found in the blog_example repository. Second: It introduces dependencies (like the AbstractController from blog_example) which are not necessary for this chapter. Maybe we should provide the code snippets via EXT:examples or just describe it with "my_extension" without generating snippets automatically. What do you think?

2022-08-22 15:53 UTC, brotkrueml reviewed
I don't like the blog_example to be used here. First: The code is not found in the blog_example repository. Second: It introduces dependencies (like the AbstractController from blog_example) which are not necessary for this chapter. Maybe we should provide the code snippets via EXT:examples or just describe it with "my_extension" without generating snippets automatically. What do you think?

I also suggest to integrate the second snippet (injection) into the first one with proper comments.

2022-08-23 18:50 UTC, linawolf commented
The code is found in the blog_example for v12. The snippets where automatically created from them.

Taking the code-snippets from the extension gurantees that they contain valid PHP and can be testet. Also it is the same example used all over. So readers don't have to get used to another extension just for the property mapper.

Yeah, dont like that AbstractController either, I will get rid of it in one of the next steps. Then this example will automatically change as well.

2022-08-24 18:41 UTC, brotkrueml approved these changes

2022-08-25 08:40 UTC, merged