Move Extension Localization Information from Extbase Fluid Book
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2093
Opened 2022-08-20 10:02 UTC by linawolf

Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/720

releases: main, 11.5

2022-08-20 19:03 UTC, brotkrueml requested changes

2022-08-20 19:03 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
> +       lib.languageTitle.value = This site has the title "Italy"
Please adjust to the same lib. Also lib.something = TEXT should be added for clarity (outside the condition with a default value).

2022-08-20 19:03 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
> +:html:`comment_header` for the default language and the languages de and zh
```suggestion
:html:`comment_header` for the default language and the languages "de" and "zh"
```

2022-08-20 19:03 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
> +:typoscript:`stdWrap` offers the :ref:`lang <t3tsref:stdwrap-lang>` property
```suggestion
:typoscript:`stdWrap` offers the :ref:`lang <t3tsref:stdwrap-lang>` property,
```

2022-08-20 19:03 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
> +with which localized strings can be provided directly by TypoScript.
```suggestion
which can be used to provide localized strings directly from TypoScript.
```

2022-08-27 08:20 UTC, linawolf commented
This PR has been split up in smaler, more manageable PRs

2022-08-27 08:20 UTC, closed without merging