Explain the new directory structure with composer-installer 5
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2279
Opened 2022-10-13 17:06 UTC by linawolf

Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/203

releases: main

2022-10-14 08:28 UTC, brotkrueml requested changes

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/ApiOverview/DirectoryStructure/Index.rst
> +    In TYPO3 v12 using the `typo3/cms-composer-installers` in version
I would rephrase it, as it is installed automatically, the sentence now can be understood as the user has to/can do something.
Maybe: "TYPO3 v12 requires typo3/cms-composer-installers in version 5."

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/ApiOverview/DirectoryStructure/Index.rst
> +Directory :file:`typo3temp/assets/` contains temporary files that should be
```suggestion
The directory :file:`typo3temp/assets/` contains temporary files that should be
```

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/ApiOverview/DirectoryStructure/Index.rst
> +    :caption: composer.json
```suggestion
    :caption: composer.json

```

The snippet is not rendered, probably because of missing empty line after caption.

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/Configuration/Typo3ConfVars/FE.rst
> +    local storages including :file:`public/fileadmin`.
```suggestion
    local storages including :file:`public/fileadmin/`.
```

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/Configuration/Typo3ConfVars/FE.rst
> +    and :file:`typo3` are also prefixed.
```suggestion
    and :file:`typo3/` are also prefixed.
```

2022-10-14 08:28 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst
> +The files for an extension are installed into a folder named :file:`vendor`
```suggestion
The files for an extension are installed into a folder named :file:`vendor/`
```

2022-10-14 10:57 UTC, linawolf commented on Documentation/ApiOverview/DirectoryStructure/Index.rst
> +    5 is mandatory. Therefore the publicly available files provided by
```suggestion
    TYPO3 v12 requires `typo3/cms-composer-installers` in version
    5. Therefore the publicly available files provided by
```

2022-10-14 10:58 UTC, linawolf commented on Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst
> +In legacy installations they are installed into
It is mentioned above, should we repeat it?

2022-10-15 08:02 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst
> +In legacy installations they are installed into
Section is about system extensions, you mention legacy, you should also mention composer. Not everyone reads from top to bottom but jumps to the according section.

2022-10-15 17:23 UTC, brotkrueml approved these changes

2022-10-15 17:27 UTC, merged