Address Changes in Evnironment API
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2294
Opened 2022-10-17 05:56 UTC by linawolf

And further changes regarding directory `typo3conf`

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/204, https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2287

2022-10-17 16:52 UTC, brotkrueml commented on Documentation/ApiOverview/Environment/Index.rst
> +For Composer-based installations, the it returns :ref:`directory-var`, in legacy
```suggestion
For Composer-based installations, it returns :ref:`directory-var`, in legacy
```

2022-10-17 17:11 UTC, brotkrueml requested changes

2022-10-17 17:11 UTC, brotkrueml commented on Documentation/Security/GuidelinesIntegrators/InstallTool.rst
> +    Even if you run TYPO3 v12 in the Composer-mode at the time of writing
```suggestion
    Even if you run TYPO3 v12 in Composer mode at the time of writing
```

Had to read it multiple times, it sounds strange without some punctuation, maybe better:

Even if you run TYPO3 v12 in the Composer-mode, the file has still to be created in folder public/typo3conf/ENABLE_INSTALL_TOOL (as at the time of writing TYPO3 v12.0.0).

But I am not sure if we have to mention it. Do you create the file before accessing the install tool without being logged-in into the backend? I always call install.php, copy the path (as I mostly don't remember the name) and make a "touch" on file system. I think, the most people will do it that way. And I assume this file will be moved into the public/project folder, so this note becomes obsolete later. Maybe we should just add a todo with a link to the forge ticket to pick it up later.

2022-10-17 17:11 UTC, brotkrueml commented on Documentation/ApiOverview/Environment/Index.rst
>  The environment provides the path to the :file:`var` folder. This folder contains
```suggestion
The environment provides the path to the :file:`var/` folder. This folder contains
```

2022-10-17 17:11 UTC, brotkrueml commented on Documentation/ApiOverview/Environment/Index.rst
> +:file:`sites/` containing the :ref:`site configuration <sitehandling>`.
```suggestion
:file:`sites/` containing the :ref:`site configurations <sitehandling>`.
```

2022-10-18 04:41 UTC, linawolf commented on Documentation/ApiOverview/Environment/Index.rst
> +    // Composer-based installations: '/home/www/my-project/var/`
done

2022-10-18 04:41 UTC, linawolf commented on Documentation/ApiOverview/Environment/Index.rst
> +- :php:`TYPO3_PATH_APP` is set to :file:`/home/www/my-project`.
removed it

2022-10-18 17:03 UTC, brotkrueml commented on Documentation/ApiOverview/Environment/Index.rst
> +The TYPO3 Core  includes an environment class that s contains all
```suggestion
The TYPO3 Core includes an environment class that contains all
```

2022-10-19 19:55 UTC, merged