[FEATURE] Add information about slot replacements and examples
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2965
Opened 2023-05-11 10:43 UTC by linawolf

Fix FQNs (Package not Mail)

See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-90249-NewPSR-14EventsForExistingPackage-relatedSignalSlots.html

2023-05-11 17:20 UTC, brotkrueml requested changes

2023-05-11 17:20 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
> +    event is only dispatched in legacy installations, not in Composer-based
"event is only dispatched" used twice in the sentence. Maybe write something like

"This event is <del>only</del> dispatched when an extension is activated in the Extension Manager, therefore starting with TYPO3 v11 it is only fired in legacy installations, not in Composer-based ..."

Also for the other events.

2023-05-11 17:20 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_Services.yaml
> +  MyVendor\MyExtension\EventListener\MyEventListener:
```suggestion
  MyVendor\MyExtension\Package\EventListener\MyEventListener:
```

2023-05-11 17:20 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
> +    :caption: EXT:my_extension/Classes/EventListener/MyEventListener.php
```suggestion
    :caption: EXT:my_extension/Classes/Package/EventListener/MyEventListener.php
```

2023-05-11 17:20 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_MyEventListener.php
> +class Setup
```suggestion
final class MyEventListener
```

2023-05-12 17:03 UTC, brotkrueml reviewed
Argh, you overrode my commit which spells "Composer" with a capital C. So, please adjust it correctly again.

2023-05-13 07:34 UTC, linawolf commented
Sorry about that, I corrected Composer to be a propper noun all over

2023-05-13 15:10 UTC, brotkrueml approved these changes

2023-05-13 17:32 UTC, merged