Important: #96332 - Extbase Validators can use dependency injection
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2983
Opened 2023-05-13 20:16 UTC by linawolf

resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/94 
releases: main, 12.4, 11.5

2023-05-14 04:04 UTC, brotkrueml requested changes
Is it necessary to backport to 11.5 as the constructor injection is possible since v12 and not with v11?

2023-05-14 04:04 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
> +Starting with TYPO3 v12 Extbase validators are capable of dependency injection
```suggestion
Starting with TYPO3 v12 Extbase validators are capable of :ref:`dependency injection <Dependency-Injection>`
```

2023-05-14 04:04 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidator.php
> +    public function __construct(private readonly Something $something) {
Hmm, can we use something like "MyService" instead of "Something"?

2023-05-14 04:04 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidatorv11v12.php
> +    public function injectSomething(Something $something)
Here too: "injectMyService" instead of "injectSomething"

2023-05-14 05:57 UTC, linawolf commented
> Is it necessary to backport to 11.5 as the constructor injection is possible since v12 and not with v11?

Right now we have no information at all on how to do di in validators in v1. We could skip the v12 stuff thougg

2023-05-15 15:24 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_Services.yaml
> +  MyVendor\MyExtenion\Validators\MyCustomValidator:
```suggestion
  MyVendor\MyExtension\Validators\MyCustomValidator:
```

2023-05-15 15:24 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidatorv11v12.php
> +namespace MyVendor\MyExtenion\Validators;
```suggestion
namespace MyVendor\MyExtension\Validators;
```

2023-05-15 15:24 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidator.php
> +namespace MyVendor\MyExtenion\Validators;
```suggestion
namespace MyVendor\MyExtension\Validators;
```

2023-05-15 15:25 UTC, brotkrueml approved these changes

2023-05-15 19:08 UTC, merged