[!!!][FEATURE] Use LanguageAspect in QuerySettings for Extbase
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #2984
Opened 2023-05-14 06:38 UTC by linawolf

resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/132

2023-05-15 15:16 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
> +    :php:`TYPO3\CMS\Core\Context\LanguageAspect` now.
```suggestion
    :php:`\TYPO3\CMS\Core\Context\LanguageAspect` now.
```

2023-05-15 15:22 UTC, brotkrueml requested changes

2023-05-15 15:22 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
> +The following methods can be used to set and get the language aspect from any
```suggestion
The following methods can be used to set and get the :ref:`language aspect <context_api_aspects_language>`  from any
```

2023-05-15 15:22 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
> +    The Extbase query settings rely on
We should mention here that the old methods still work in v12, but are deprecated.

2023-05-15 15:22 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_LanguageAspect.php
> +
We should add strict types header.

2023-05-15 15:22 UTC, brotkrueml commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_LanguageAspect.php
> +class MyRepository extends Repository
```suggestion
final class MyRepository extends Repository
```

2023-05-15 19:13 UTC, linawolf commented on Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_LanguageAspect.php
> +
done

2023-05-16 04:46 UTC, brotkrueml approved these changes

2023-05-16 15:24 UTC, merged