[DOCS] Add example for IsContentUsedOnPageLayoutEvent PSR-14 event
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #3480
Opened 2023-09-26 20:27 UTC by garvinhicking

(based on EXT:container and a slack message from Stefan Bürk)

2023-09-26 20:53 UTC, garvinhicking commented
(Second commit because I used `getIsUsed` improperly; in fact it was leftover code from the hook, which isn't needed in the PSR-14 event)

2023-09-27 04:26 UTC, brotkrueml requested changes
@garvinhicking Thanks for your contribution. I would like to address some changes:
- Please use as blueprint one of the other events, like https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Events/Events/Backend/ModifyImageManipulationPreviewUrlEvent.html#example
- please add the text to the example section like in other events
- as we merge this also to 12.4 branch don't use the PHP attribute for now. In a follow-up we adjust the example to use the attribute
- have also a look at the Services.yaml example in the linked event from above, we reduce some of the configuration to a comment
- we don't use the event tag anymore as this is superfluous when using the type declaration of the event's invoke method

2023-09-27 05:19 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_ContentUsedOnPage.php
> +        if ($record['colPos'] === 999 && !empty($record['tx_myext_content_parent'])) {
```suggestion
        $record = $event->getRecord();
        if ($record['colPos'] === 999 && !empty($record['tx_myext_content_parent'])) {
```

2023-09-27 09:51 UTC, sbuerk commented on Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_ContentUsedOnPage.php
> +#[AsEventListener(
The `AsEventListener` attribute is a new feature for main (13.0).

Using the attribute AND the registration over `Services.yaml` is duplicated.

Not sure about the policy for the documentation, but:

* remove the `Services.yaml` for main and for the backport use the `Services.yaml` and drop the PHP attribute usage
* or simply use only the `Services.yaml` version

2023-09-27 10:18 UTC, sbuerk commented
FYI - I created a core patch to add examples to the corresponding changelog rest file:

81263: [DOCS] Add example for `Page Module` PSR-14 events | https://review.typo3.org/c/Packages/TYPO3.CMS/+/81263

2023-09-27 15:25 UTC, brotkrueml commented on Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst
> +The corresponding event listener class:
```suggestion
Read :ref:`how to configure dependency injection in extensions <dependency-injection-in-extensions>`.

The corresponding event listener class:
```

2023-09-27 15:29 UTC, merged