[FEATURE] Document the ModuleTemplateFactory
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #4414
Opened 2024-05-17 08:27 UTC by linawolf

Releases: main, 12.4

2024-05-17 19:28 UTC, froemken requested changes

2024-05-17 19:28 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/ModuleTemplateFactory.rst
> +.. include:: /Includes.rst.txt
2 spaces

2024-05-17 19:28 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/ModuleTemplateFactory.rst
> +:php:`\TYPO3\CMS\Backend\Template\ModuleTemplate.`
Dot should not be part of class

2024-05-17 19:28 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController.php
> +
Remove empty space

2024-05-17 19:28 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplateFactory.rst.txt
> +..  php:namespace::  TYPO3\CMS\Backend\Template
After `::` just one space

2024-05-17 19:28 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplateFactory.rst.txt
> +    ..  php:method:: create(Psr\Http\Message\ServerRequestInterface $request)
Add `\` in front of class

2024-05-18 04:27 UTC, linawolf commented
Solved with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4416

2024-05-18 04:27 UTC, closed without merging