[FEATURE] Document ModuleTemplate
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #4416
Opened 2024-05-17 10:42 UTC by linawolf

2024-05-17 10:43 UTC, linawolf commented
Depends on #4414

2024-05-17 19:24 UTC, froemken requested changes

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/ModuleTemplate.rst
> +to create instances of a :php:`\TYPO3\CMS\Backend\Template\ModuleTemplate.`.
Remove dot behind class

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController_ModuleTemplate.php
> +    private function getLanguageService(): LanguageService
Add space before

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController_ModuleTemplate.php
> +
Remove empty space

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplate.rst.txt
> +    ..  php:method:: addFlashMessage(string $messageBody, string $messageTitle = '', TYPO3\CMS\Core\Type\ContextualFeedbackSeverity $severity = \TYPO3\CMS\Core\Type\ContextualFeedbackSeverity::OK, bo
Missing `\` in front of class

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplate.rst.txt
> +    ..  php:method:: setFlashMessageQueue(TYPO3\CMS\Core\Messaging\FlashMessageQueue $flashMessageQueue)
Missing `\` in front of class

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController.php
> +
Remove empty space

2024-05-17 19:24 UTC, froemken commented on Documentation/ApiOverview/Backend/BackendModules/ModuleTemplate.rst
> +.. include:: /Includes.rst.txt
2 spaces

2024-05-18 04:25 UTC, linawolf commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController_ModuleTemplate.php
> +    private function getLanguageService(): LanguageService
```suggestion

    private function getLanguageService(): LanguageService
```

2024-05-18 04:25 UTC, linawolf commented on Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplate.rst.txt
> +    ..  php:method:: addFlashMessage(string $messageBody, string $messageTitle = '', TYPO3\CMS\Core\Type\ContextualFeedbackSeverity $severity = \TYPO3\CMS\Core\Type\ContextualFeedbackSeverity::OK, bo
These files are auto-generated...

2024-05-18 04:26 UTC, linawolf commented
@froemken applied suggested changes

2024-05-19 14:14 UTC, brotkrueml commented on Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController.php
> +    protected function initializeModuleTemplate(ServerRequestInterface $request): ModuleTemplate
Why not override initializeAction() method? This is always called before an action. So no need to call initialiteModuleTemplate() manually in each action - which is error-prone (can be left out unintended). Just set $this->moduleTemplate and the use it in the action.

2024-05-19 14:14 UTC, brotkrueml commented on Documentation/ApiOverview/Backend/BackendModules/ModuleTemplate.rst
> +Backend controllers should use :ref:`ModuleTemplateFactory:create <ModuleTemplateFactory>`
```suggestion
Backend controllers should use :ref:`ModuleTemplateFactory::create() <ModuleTemplateFactory>`
```

2024-05-19 15:43 UTC, brotkrueml approved these changes

2024-05-19 18:30 UTC, merged