[TASK] Overhaul Backend UriBuilder page
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #4545
Opened 2024-06-16 06:55 UTC by linawolf

In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/940

Releases: main, 12.4, 11.5

2024-06-16 14:05 UTC, froemken requested changes

2024-06-16 14:05 UTC, froemken commented on Documentation/ApiOverview/Backend/UriBuilder.rst
>     web routing UriBuilder and can only be used for frontend links.
The `hint` is indented with 4 spaces. Would be good to keep the following indented with 4 spaces, too.

```suggestion
    Make sure to use :code:`\TYPO3\CMS\Backend\Routing\UriBuilder` to create
    backend links and not :code:`\TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder`.

    The variable available as :code:`$this->uriBuilder` in a controller is the
    web routing UriBuilder and can only be used for frontend links.
```

2024-06-16 14:07 UTC, froemken commented
Hello @linawolf 

Quote: `The example from blog_example also need to be adjusted`

I don't get it as `columnsOnly` is currently not used in `blog_example`

Stefan

2024-06-17 04:10 UTC, linawolf commented
> Quote: `The example from blog_example also need to be adjusted`
> 
> I don't get it as `columnsOnly` is currently not used in `blog_example`

No but the example is outdated in General (No DI, not using a valid view for the backend etc)

2024-06-17 05:15 UTC, linawolf commented
See also https://github.com/TYPO3-Documentation/t3docs-examples/pull/276

2024-06-17 06:53 UTC, froemken approved these changes

2024-06-17 07:52 UTC, merged