[TASK] Improve definition of "frontend plugins"
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #4598
Opened 2024-07-10 12:02 UTC by garvinhicking

Originating in a slack discussion: https://typo3.slack.com/archives/C079VNXERKN/p1720596676302029

Just a first draft we can maybe improve on, either with follow-ups or here.

2024-07-10 14:41 UTC, Alagts approved these changes

2024-07-10 17:26 UTC, fe-hicking commented on Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
> +only, using custom content object renderers.
More like generally implementing things like FLUIDTEMPLATE on its own, but yours would also be ok.. i wanted to keep this unspecific to not overcomplicate the intro, and just mention cobj renderers like what fsc/csc implements?

2024-07-12 08:24 UTC, garvinhicking commented on Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
> +For a long time, TYPO3 provided a "General Plugin" to be selected as a
Adjusted, ok?

2024-07-12 08:24 UTC, garvinhicking commented on Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
> +only, using custom content object renderers.
Agreed!

2024-07-12 09:54 UTC, linawolf submitted a review, later dismissed

2024-07-12 10:31 UTC, mbrodala requested changes

2024-07-12 11:08 UTC, mbrodala approved these changes

2024-07-12 11:08 UTC, merged

2024-07-12 11:37 UTC, garvinhicking commented
Created manual backports and a follow-up. Seems my last commit made in the GitHub UI here didn't make it through or was kiled in a rebase. -.-