[TASK] Improve introduction into content elements and plugins
TYPO3-Documentation/TYPO3CMS-Reference-CoreApi pull request #4725
Opened 2024-09-08 13:04 UTC by linawolf

To keep the PR small I only worked on the first section

Releases: main, 12.4

2024-09-09 18:08 UTC, format-gmbh requested changes

2024-09-09 18:08 UTC, format-gmbh commented on Documentation/ApiOverview/ContentElements/Index.rst
> +        A plugin in TYPO3 is a more complex module, typically providing dynamic
```suggestion
A plugin in TYPO3 is more complex, typically providing dynamic
```

2024-09-09 18:25 UTC, format-gmbh approved these changes

2024-09-09 18:26 UTC, merged

2024-09-10 07:30 UTC, Oktopuce commented on Documentation/ApiOverview/ContentElements/Index.rst
> +        the plugin can be an Extbase plugin or a plain plugin.
Haven't seen the term "plain plugin" before in documentation.
May be you can change this sentence 

> "Depending on the technology used in the controller the plugin can be an Extbase plugin or a plain plugin."

with:

> Plugins can be implemented using Extbase controller but can also be done with TYPO3 Core native functionalities.